// src/repositories/contactRepository.ts
//
// CONTRACT for contact-form data access. Same pattern as userRepository.ts:
// types + interface only, no storage logic. Matches the frontend's
// ContactFormPayload shape (my-app/src/mocks/mockApi.ts) so the eventual
// fetch swap (Handbook Section 09) needs no reshaping in either direction.

/**
 * A stored contact form submission.
 */
export interface ContactSubmission {
  id: string;
  fullName: string;
  email: string;
  phone: string;
  message: string;
  createdAt: string;
}

/**
 * The fields a caller must supply to record a new submission.
 * `id` and `createdAt` are generated by the repository on creation.
 */
export type NewContactSubmission = Omit<ContactSubmission, "id" | "createdAt">;

/**
 * The contract every contact repository implementation must satisfy.
 * Storage and retrieval only — validating the incoming form data (name
 * length, phone format, message length, etc.) belongs to Zod at the
 * controller boundary (Handbook Section 08), not here.
 */
export interface ContactRepository {
  /** Persist a new submission and return the full stored record. */
  create(submission: NewContactSubmission): Promise<ContactSubmission>;

  /** Retrieve all submissions, newest first. */
  findAll(): Promise<ContactSubmission[]>;

  /** Find a single submission by id, or null if it doesn't exist. */
  findById(id: string): Promise<ContactSubmission | null>;
}