// src/repositories/userRepository.ts
//
// This file is the CONTRACT for user data access. It contains types and an
// interface only — no storage logic lives here.
//
// Per the Repository Pattern (Handbook Section 05): services depend on this
// interface, never on a specific implementation. Today the implementation is
// memoryUserRepository.ts (in-memory array). In Week 4 it becomes a Prisma
// repository backed by PostgreSQL. As long as both implementations satisfy
// this same interface, nothing outside repositories/ has to change.

/**
 * The shape of a user record as stored by the backend.
 *
 * Note: `passwordHash` is the bcrypt hash, never the plaintext password.
 * Hashing happens in the service layer (authService) — the repository's job
 * is only to store/retrieve whatever it's given, not to decide how a
 * password should be protected.
 */
export interface User {
  id: string;
  fullName: string;
  email: string;
  passwordHash: string;
  role: "Student" | "Trainer" | "Company" | "Admin";
  createdAt: string;
}

/**
 * The fields a caller must supply to create a new user.
 * `id` and `createdAt` are generated by the repository on creation.
 */
export type NewUser = Omit<User, "id" | "createdAt">;

/**
 * A user record safe to hand back to the client — no password hash included.
 */
export type SafeUser = Omit<User, "passwordHash">;

/**
 * The contract every user repository implementation must satisfy.
 * Only storage and retrieval belong here — no business rules
 * (e.g. "is this email already taken" belongs in the service layer, which
 * calls `emailExists` and then decides what to do with the answer).
 */
export interface UserRepository {
  /** Find a user by email, or null if no such user exists. */
  findByEmail(email: string): Promise<User | null>;

  /** Find a user by id, or null if no such user exists. */
  findById(id: string): Promise<User | null>;

  /** Whether a user with this email already exists. */
  emailExists(email: string): Promise<boolean>;

  /** Persist a new user and return the full stored record. */
  create(newUser: NewUser): Promise<User>;
}